spring.application.name=privadocai
server.port=8080

security.jwt.secret=12847b0f5993199eac166e652541a1881709fbe015b22952dde71df08390c48b
security.jwt.expiration-ms=900000
security.jwt.refresh-expiration-ms=604800000

spring.datasource.url=jdbc:postgresql://localhost:5432/priva-db
spring.datasource.username=priva-admin
spring.datasource.password=Ldwpe30idn03@#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.storage.upload-dir=./documents
spring.servlet.multipart.max-file-size=10MB

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4
spring.ai.ollama.embedding.options.model=nomic-embed-text
